title: Abhishek Nagekar
description: Web & Security Engineer
site_title: '@abhn'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com

# absolute or relative
profile_picture: /assets/images/pp.jpeg