title: 김현혜
description: ''
site_title: ''

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: 김현혜
blog_url: https://techhyeondev.github.io/portfolio/
email: rlausp94@naver.com

# absolute or relative
profile_picture: assets/images/profile.jpg

