title: Abhishek Nagekar
description: Web & Security Engineer
site_title: '@abhn'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpeg

# Google Analytics ID
google_analytics: 